asdasdas:
- changed-files:
  - any-glob-to-any-file: 
    - 'README.md'
    - 'RELEASES.md'
    - 'docs/**/*'

source:
- changed-files:
  - any-glob-to-any-file: 'src/**/*'

Configurations:
- changed-files:
  - any-glob-to-any-file: 
    - 'tsconfig.json'
    - 'vite.config.ts'
    - 'package.json'
    - 'pnpm-lock.yaml'

AnyChange:
- changed-files:
  - any-glob-to-any-file: '**/*'