name: Publish to NPM with pnpm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm 🔄
        run: npm install -g pnpm@latest
      - name: Install dependencies with pnpm 🛠️
        run: pnpm install --frozen-lockfile
      - name: Build with pnpm (if applicable) 🔧
        run: pnpm ci
      - name: Publish package on NPM with pnpm 📦
        run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

          